name = "myExample"
uuid = "f5c903b2-b27e-4991-938a-7558b82fa026"
authors = ["Radek"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
